{
 "title": "votatron",
 "time": { "from": "2020-12-14T03:00:00.000Z", "to": "now" },
 "refresh": "5s",
 "templating": {
  "list": [
   { "name": "Filters" }
  ]
 },
 "panels": [
  {
   "title": "Votos/scraper",
   "type": "graph",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "votatron_processed_votes_total" }
   ]
  },
  {
   "title": "Worker/Votes",
   "type": "table",
   "gridPos": { "h": 10, "w": 4, "x": 0, "y": 8 },
   "targets": [
    {
     "expr": "increase(votatron_processed_votes_total[24h])"
    }
   ]
  },
  {
   "title": "Workers",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 5, "x": 4, "y": 8 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "expr": "sum(prometheus_target_scrape_pool_targets)-1"
    }
   ]
  },
  {
   "title": "Votos/tempo",
   "type": "graph",
   "gridPos": { "h": 10, "w": 15, "x": 9, "y": 8 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(increase(votatron_processed_votes_total[24h]))"
    }
   ]
  },
  {
   "title": "Total Votos",
   "type": "singlestat",
   "gridPos": { "h": 6, "w": 5, "x": 4, "y": 12 },
   "format": "none",
   "valueName": "total",
   "targets": [
    {
     "expr": "sum(increase(votatron_processed_votes_total[48h]))"
    }
   ]
  }
 ]
}